spring.application.name=biblio2
# Configuracion de H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Configuracion de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Credenciales de desarrollo
spring.security.user.name=Omora
spring.security.user.password={noop}Jinxvi2205
# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
# Cargar data.sql despues de crear las tablas con JPA
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
